### PR TITLE
Add shellcheck to check the portability of the shell script

### PR DESCRIPTION
**Pull request by umireon**
**Please enable GitHub Actions on this repository**

[Shellcheck](https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md) is the best way to write an ultimately portable shell script as far as I know.

The example of checking is here:
https://github.com/umireon/get/runs/3353432552?check_suite_focus=true

### CODE REVIEW

**Comment by zkochan** [comment]
actions are on. I don't know why they don't run for this

**Comment by umireon** [comment]
This was because I was the first-time contributor for this repository.
https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/

**Comment by zkochan** [comment]
It was because you only specified it to run on main https://github.com/pnpm/get/commit/4fd5cba8e2e8cdde73d51693ae0c6108214a5e7d

**Comment by umireon** [comment]
Any PR to main (like this PR) should run the action. I wrote so.

```yaml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
```

https://github.com/pnpm/get/pull/3/files#diff-549859aac5bcaebdf605d3ffd525377f2b314b5cc6eb4ebad490bd2cc52617a7R6-R7

**Pull request merged**
