### PR TITLE
Fancy logging

### PR DESCRIPTION
**Pull request by umireon**
Just for testing GitHub Actions

### CODE REVIEW

**Comment by umireon** [comment]
@zkochan Please note that `/bin/sh` exists everywhere because it is part of the POSIX standard but some major distributions such as alpine and busybox in Docker Hub do not have bash by default.
In addition, `/bin/sh` in Ubuntu is dash so that we would need the dash support.
We cannot ignore dash.

**Comment by zkochan** [comment]
sure, but I did not know how to fix all the linting issues.

We should probably add tests that run the script on different linux distros

**Comment by umireon** [comment]
@zkochan I know how we can fix the linting errors and I can help you 😉

**Comment by zkochan** [comment]
oh, ok
that would be really great!

**Pull request closed without merging**
